"""Canonical Application Model schemas.

This is the internal protocol. All ATS systems must map into these types.
"""

from datetime import datetime
from enum import Enum
from typing import Any, Optional

from pydantic import BaseModel, Field, field_validator

from jobcli.profile.schemas import ATSType


class FieldSemanticType(str, Enum):
    """Semantic type taxonomy for application fields.

    This is THE authoritative list of field types the system understands.
    When adding a new type, also update:
    - validators.py validation rules
    - mappers.py resume field mappings
    """

    # Personal Identity
    EMAIL = "email"
    PHONE = "phone"
    FIRST_NAME = "first_name"
    LAST_NAME = "last_name"
    FULL_NAME = "full_name"
    MIDDLE_NAME = "middle_name"
    PREFERRED_NAME = "preferred_name"

    # Location
    ADDRESS_LINE_1 = "address_line_1"
    ADDRESS_LINE_2 = "address_line_2"
    CITY = "city"
    STATE = "state"
    COUNTRY = "country"
    ZIP_CODE = "zip_code"

    # Professional Links
    LINKEDIN_URL = "linkedin_url"
    GITHUB_URL = "github_url"
    PORTFOLIO_URL = "portfolio_url"
    WEBSITE_URL = "website_url"

    # Work Authorization
    WORK_AUTHORIZED = "work_authorized"
    REQUIRE_SPONSORSHIP = "require_sponsorship"
    VISA_STATUS = "visa_status"
    CITIZENSHIP = "citizenship"

    # Education
    SCHOOL_NAME = "school_name"
    DEGREE_TYPE = "degree_type"
    FIELD_OF_STUDY = "field_of_study"
    GRADUATION_YEAR = "graduation_year"
    GRADUATION_DATE = "graduation_date"
    GPA = "gpa"

    # Experience
    COMPANY_NAME = "company_name"
    JOB_TITLE = "job_title"
    START_DATE = "start_date"
    END_DATE = "end_date"
    CURRENT_ROLE = "current_role"
    YEARS_OF_EXPERIENCE = "years_of_experience"

    # Documents
    RESUME_UPLOAD = "resume_upload"
    COVER_LETTER_UPLOAD = "cover_letter_upload"
    TRANSCRIPT_UPLOAD = "transcript_upload"
    OTHER_DOCUMENT_UPLOAD = "other_document_upload"

    # Demographics (optional, comply with local laws)
    GENDER = "gender"
    PRONOUNS = "pronouns"
    RACE_ETHNICITY = "race_ethnicity"
    VETERAN_STATUS = "veteran_status"
    DISABILITY_STATUS = "disability_status"

    # Application-Specific
    REFERRAL_SOURCE = "referral_source"
    HEAR_ABOUT_US = "hear_about_us"
    WHY_INTERESTED = "why_interested"
    SALARY_EXPECTATION = "salary_expectation"
    EARLIEST_START_DATE = "earliest_start_date"
    WILLING_TO_RELOCATE = "willing_to_relocate"

    # Custom/Unknown
    CUSTOM_TEXT = "custom_text"
    CUSTOM_SELECT = "custom_select"
    CUSTOM_BOOLEAN = "custom_boolean"
    UNKNOWN = "unknown"


class FieldSource(str, Enum):
    """Where the field value originated."""

    RESUME_JSON = "resume_json"           # Extracted from resume.json
    MEMORY_HIGH_CONFIDENCE = "memory_high_confidence"  # Learned, confidence >= 0.6, success >= 3
    MEMORY_LOW_CONFIDENCE = "memory_low_confidence"    # Learned but below threshold
    LLM_REASONING = "llm_reasoning"       # Generated by LLM from context
    HUMAN_PROVIDED = "human_provided"     # User entered manually
    ATS_PREFILLED = "ats_prefilled"       # Already on page (via extension or site)
    RULE_BASED = "rule_based"             # Deterministic rule matched
    DEFAULT_VALUE = "default_value"       # Fallback/safe default


class ValidationSeverity(str, Enum):
    """Validation result severity."""

    OK = "ok"              # Validation passed
    WARNING = "warning"    # Suspicious but not blocking
    ERROR = "error"        # Validation failed, cannot submit


class ConfidenceScore(BaseModel):
    """Confidence tracking for a field value.

    Confidence = P(this value will be accepted by the ATS form validation).
    Derived from: source reliability, validation rules, past success rate.
    """

    value: float = Field(..., ge=0.0, le=1.0, description="Confidence score [0.0, 1.0]")
    source_weight: float = Field(..., ge=0.0, le=1.0, description="How much to trust this source")
    validation_passed: bool = Field(..., description="Did semantic validation pass?")
    historical_success_rate: Optional[float] = Field(None, ge=0.0, le=1.0, description="Success rate from memory")

    @field_validator("value")
    @classmethod
    def _clamp_confidence(cls, v: float) -> float:
        """Ensure confidence stays in [0.0, 1.0]."""
        return max(0.0, min(1.0, v))


class ValidationResult(BaseModel):
    """Result of validating an ApplicationField value."""

    severity: ValidationSeverity
    message: str = Field(..., description="Human-readable validation message")
    expected_format: Optional[str] = Field(None, description="What format was expected (e.g., 'valid email')")
    actual_value_preview: Optional[str] = Field(None, description="Preview of actual value (sanitized)")


class ApplicationField(BaseModel):
    """Canonical representation of a single application field.

    This is the internal protocol. Every ATS-specific field must map into this schema.

    Example:
        {
            "field_id": "candidate_email",
            "semantic_type": "email",
            "raw_label": "Email Address *",
            "normalized_label": "email address",
            "required": true,
            "value": "jane@example.com",
            "confidence": {...},
            "source": "resume_json",
            "validation": {...},
            "ats_selector": "input[name='email']",
            "ats_type": "greenhouse"
        }
    """

    # Identity
    field_id: str = Field(..., description="Unique ID within this session (e.g., 'candidate_email')")
    semantic_type: FieldSemanticType = Field(..., description="What this field means semantically")

    # Labeling (as seen on the ATS page)
    raw_label: str = Field(..., description="Original label from ATS (e.g., 'Email Address *')")
    normalized_label: str = Field(..., description="Normalized for matching (lowercase, no punctuation)")

    # Field Properties
    required: bool = Field(False, description="Is this field mandatory?")
    input_type: str = Field("text", description="HTML input type: text, select, checkbox, file, etc.")
    placeholder: Optional[str] = Field(None, description="Placeholder text if present")
    options: list[str] = Field(default_factory=list, description="For select/radio: available options")

    # Value & Provenance
    value: Optional[str] = Field(None, description="Current field value")
    source: FieldSource = Field(..., description="Where this value came from")
    confidence: ConfidenceScore = Field(..., description="How confident are we in this value?")

    # Validation
    validation: ValidationResult = Field(..., description="Result of semantic validation")

    # ATS-Specific (for execution)
    ats_selector: Optional[str] = Field(None, description="CSS/XPath selector for this field on the ATS page")
    ats_type: ATSType = Field(..., description="Which ATS platform this field belongs to")

    # Metadata
    page_index: int = Field(0, description="Which page/step of multi-page form (0-indexed)")
    timestamp: datetime = Field(default_factory=datetime.utcnow, description="When this field was detected")


class ExecutionAction(BaseModel):
    """A single atomic action to execute on the browser.

    This is the output of the canonical model after validation.
    The execution engine converts this into Playwright commands.
    """

    action_type: str = Field(..., description="fill, click, select, upload, etc.")
    target_field_id: str = Field(..., description="ApplicationField.field_id this action targets")
    selector: str = Field(..., description="CSS/XPath selector")
    value: Optional[str] = Field(None, description="Value to fill/select (if applicable)")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Confidence this action will succeed")
    required_pre_check: bool = Field(True, description="Should we verify field is empty before filling?")
    verify_after: bool = Field(True, description="Should we read back value after action?")


class ApplicationSession(BaseModel):
    """Complete state of an application session.

    This is the single source of truth. All decisions route through this model.

    Usage:
        session = ApplicationSession(job_id=123, ats_type=ATSType.GREENHOUSE)
        session.add_field(ApplicationField(...))
        session.validate_all()
        actions = session.get_pending_actions()
    """

    # Session Identity
    session_id: str = Field(..., description="Unique session ID (UUID)")
    job_id: int = Field(..., description="Foreign key to jobs table")
    ats_type: ATSType = Field(..., description="Which ATS platform")
    job_url: str = Field(..., description="Application URL")

    # Session State
    started_at: datetime = Field(default_factory=datetime.utcnow)
    current_page_index: int = Field(0, description="Current wizard step (0-indexed)")
    total_pages: int = Field(1, description="Total wizard steps detected")

    # Fields
    fields: list[ApplicationField] = Field(default_factory=list, description="All detected fields")
    completed_field_ids: set[str] = Field(default_factory=set, description="Field IDs successfully filled")
    failed_field_ids: set[str] = Field(default_factory=set, description="Field IDs that failed execution")

    # Execution Plan
    pending_actions: list[ExecutionAction] = Field(default_factory=list, description="Actions queued for execution")
    executed_actions: list[ExecutionAction] = Field(default_factory=list, description="Actions already executed")

    # Telemetry
    snapshots: list[dict[str, Any]] = Field(default_factory=list, description="Session state snapshots for replay")

    model_config = ConfigDict(arbitrary_types_allowed=True)

    def add_field(self, field: ApplicationField) -> None:
        """Add a field to the session (deduped by field_id)."""
        # Remove any existing field with same ID
        self.fields = [f for f in self.fields if f.field_id != field.field_id]
        self.fields.append(field)

    def get_field(self, field_id: str) -> Optional[ApplicationField]:
        """Retrieve a field by ID."""
        for field in self.fields:
            if field.field_id == field_id:
                return field
        return None

    def get_required_empty_fields(self) -> list[ApplicationField]:
        """Get all required fields that still need values."""
        return [
            f for f in self.fields
            if f.required
            and f.page_index == self.current_page_index
            and not f.value
            and f.field_id not in self.completed_field_ids
        ]

    def get_failed_fields(self) -> list[ApplicationField]:
        """Get fields that failed validation or execution."""
        return [
            f for f in self.fields
            if f.field_id in self.failed_field_ids
            or f.validation.severity == ValidationSeverity.ERROR
        ]

    def mark_completed(self, field_id: str) -> None:
        """Mark a field as successfully filled."""
        self.completed_field_ids.add(field_id)
        if field_id in self.failed_field_ids:
            self.failed_field_ids.remove(field_id)

    def mark_failed(self, field_id: str) -> None:
        """Mark a field as failed."""
        self.failed_field_ids.add(field_id)
        if field_id in self.completed_field_ids:
            self.completed_field_ids.remove(field_id)

    def snapshot(self) -> dict[str, Any]:
        """Create a point-in-time snapshot for telemetry/replay."""
        snapshot = {
            "timestamp": datetime.utcnow().isoformat(),
            "current_page": self.current_page_index,
            "fields_total": len(self.fields),
            "fields_completed": len(self.completed_field_ids),
            "fields_failed": len(self.failed_field_ids),
            "pending_actions": len(self.pending_actions),
            "fields": [f.model_dump(mode="json") for f in self.fields],
        }
        self.snapshots.append(snapshot)
        return snapshot

    def validate_all(self) -> list[ApplicationField]:
        """Validate all fields and return those with errors."""
        # Validation logic will be in validators.py
        return self.get_failed_fields()

    def get_pending_actions(self) -> list[ExecutionAction]:
        """Get actions ready to execute (not yet executed, on current page)."""
        return [
            a for a in self.pending_actions
            if a not in self.executed_actions
        ]
